Numpy
Sebuah library python yang digunakan untuk komputasi numerik,khusunya ilmu data.

1. Array
2. Add,remove,sort and delete
3. shape and size
4. indexing and slicing
5. Convert array 1D to 2D or 3D

In [1]:
#IMPORT LIBRARY NUMPY
import numpy as np

1. Array

In [2]:
example = np.array([1,2,3,4,5])
example

array([1, 2, 3, 4, 5])

In [4]:
#zeros array
zero = np.zeros(3)
zero

array([0., 0., 0.])

In [6]:
#array 2D with numpy
twoD = np.array([[1,2,3],[4,5,6]])
twoD

array([[1, 2, 3],
       [4, 5, 6]])

2. Add, remove,and sort

In [7]:
animal = np.array(['Cat','Bird','Cow'])
animal

array(['Cat', 'Bird', 'Cow'], dtype='<U4')

In [9]:
#add
addAnimal = np.append(animal,['Snake','Elephant'])
addAnimal

array(['Cat', 'Bird', 'Cow', 'Snake', 'Elephant'], dtype='<U8')

In [11]:
#sort
sortAnimal = np.sort(addAnimal)
sortAnimal

array(['Bird', 'Cat', 'Cow', 'Elephant', 'Snake'], dtype='<U8')

In [12]:
#remove
removeAnimal = np.delete(sortAnimal,3)
removeAnimal

array(['Bird', 'Cat', 'Cow', 'Snake'], dtype='<U8')

3. Shape and size

In [13]:
#shape
city = np.array([
        ['Majalengka','Bandung','Karawang'], ['Cirebon','Indramayu','Subang'],['Purwakarta','Cikarang','Bekasi']
    ])

city

array([['Majalengka', 'Bandung', 'Karawang'],
       ['Cirebon', 'Indramayu', 'Subang'],
       ['Purwakarta', 'Cikarang', 'Bekasi']], dtype='<U10')

In [14]:
#cek array dimension
city.ndim

2

In [15]:
#cek all value in array
city.size

9

In [16]:
#cek tuple in array
city.shape

(3, 3)

Ini berarti terdapat 3 baris dan 3 kolom

4.Indexing and Slicing

In [18]:
angka = np.arange(10)
angka

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
print(angka[7:])

[7 8 9]


In [20]:
print(angka[3:7])

[3 4 5 6]


Convert array from 1D to 2D,or 3D

In [39]:
#1 Dimension
value = np.arange(16)
value

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
#Two Dimension
twoDim = value.reshape(4,4)
twoDim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
twoDim.ndim

2

In [45]:
value2 = np.arange(8)
value2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
#Three DImension
threeDim = value2.reshape(2,2,2)
threeDim

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
threeDim.ndim

3