In [2]:
import numpy as np

SOAL 1
- Buatlah sebuah array dengan perintah arrange yang nilai start dan end adalah sebuah input!
- Dari array yang terbentuk tersebut, buatlah versi 2 dan 3 dimensinya!

In [4]:
#array dengan perintah arrange yang nilai start dan end adalah sebuah input!
def array(start, end):
    return np.arange(start, end)

#input start dan end
start = int(input("Masukkan nilai start: "))
end = int(input("Masukkan nilai end: "))

#memanggil fungsi array
x = array(start, end)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [5]:
#ubah ke array 2 dimensi
x.reshape(3,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [6]:
#3D
x.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

SOAL 2
Buatlah sebuah array 1 dimensi dari data random integer sebanyak “n”, dimana “n” tersebut adalah sebuah input !
Batasan random juga ditentukan dalam input.
Ubahlah array 1 dimensi tersebut ke dalam bentuk 2 dimensi atau matrix!
Setelah diubah ke bentuk 2 dimensi, setiap barisnya baliklah urutan datanya! Misalnya dari 1, 2, 3 menjadi 3, 2, 1.

In [7]:
#input
n = int(input("Banyak data: "))
a = int(input("Mulai: "))
b = int(input("Selesai: "))

In [8]:
#bangkitkan array 1 dimensi dari random integer
arr = np.random.randint(a, b, n)
print('array 1D : ',arr)

array 1D :  [16 49 39 13 49 21  2 16 39 17 17  8 22 28 28 34]


In [9]:
#Ubah ke 2D
arr = arr.reshape(4,4)
print(arr)

[[16 49 39 13]
 [49 21  2 16]
 [39 17 17  8]
 [22 28 28 34]]


In [10]:
#Tukar posisi
arr = arr[:, ::-1]
print(arr)

[[13 39 49 16]
 [16  2 21 49]
 [ 8 17 17 39]
 [34 28 28 22]]


SOAL 3
Buatlah sebuah array 2 dimensi dengan ukuran 10 x 10!
Isi dari array tersebut adalah:
• Sisi luarnya merupakan angka 4.
• Selain sisi luar, angka yang ditampilkan adalah 0.

In [11]:
#array 10x10
x = np.zeros((10,10))

#isi tiap sisi
x[0] = 4 #atas
x[-1] = 4 #bawah
x[:,0] = 4 #kiri
x[:,-1] = 4 #kanan

print(x)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]
